### ISSUE TITLE
[FEATURE] - make drop_schemas_automation more flexible

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_fivetran_utils#109]
see discussion in https://github.com/fivetran/dbt_fivetran_utils/pull/106#discussion_r1169254689

**Comment by fivetran-joemarkiewicz** [comment]
After thinking more critically about this Feature Request I don't believe we should continue to move forward with keeping this in the backlog for a future update. The drop schema automation works as expected and has not been an issue since its implementation.

I worry having the automation leverage a fuzzy matching criteria could result in schemas not related to the model directly being dropped and therefore causing failures in existing buildkite runs for other models. I think this should suffice for now.

Possibly a better alternative would be to have each run of a buildkite job create a custom schema that is then created and dropped in the same job run. That would be applied to the packages themselves though. Therefore, I will close out this FR.
