### ISSUE TITLE
BUG: v0.3.6 causing compilation error in dbt 1.0.4

### ISSUE THREAD

**Issue by chili-aaron** [fivetran/dbt_fivetran_utils#73]
Hello team,

Our team is using the following packages inside of our dbt Cloud instance:

  - package: fivetran/zendesk_source
    version: [">=0.6.0", "<0.7.0"]

  - package: fivetran/zendesk
    version: [">=0.8.0", "<0.9.0"]

With the release of v0.3.6 of the dbt_fivetran_utils, we're getting a compilation error for the new get_column_names_only macro.  Manually reverting to the v0.3.5 package via our packages.yml resolves the error in the meantime.

Error message from our dbt runs:

15:28:01  Running with dbt=1.0.4
15:28:01  Partial parse save file not found. Starting full parse.
Compilation Error
  In dispatch: No macro named 'get_column_names_only' found
      Searched for: 'snowflake__get_column_names_only', 'default__get_column_names_only'

**Comment by chili-aaron** [comment]
@fivetran-reneeli - figured I'd give you a heads up. :)

**Comment by fivetran-joemarkiewicz** [comment]
Hi @chili-aaron would you be able to try again.

We just rolled back the last updates and the error should be resolved now with the latest release.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for the update @chili-aaron! 

I will be closing this issue since the error is resolved. I did want to call out that after this speed bump this morning we are planning to break out our Fivetran Utils package so issues like this will not happen in the future. I again apologize for this issue this morning and really appreciate you raising this to our attention.

Thanks!
